spring:
  config:
    activate:
      on-profile: qa

build:
  version: "2.0"

accounts:
  message: "Welcome to accounts microservive QA APIs "
  contactDetails:
    name: "SAlly Joe - Tester"
    email: "sjoe@nowhere.com"
  onCallSupport:
    - (801) 666-2345
    - (801) 666-9876