build:
  version: "3.0"

accounts:
  message: "Welcome to accounts microservive related DEV APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@nowhere.com"
  onCallSupport:
    - (801) 555-1234
    - (801) 523-1345