#server:
#  port: 8080
#spring:
#  application:
#    name: "accounts"
#  profiles:
#    active: "prod"
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: ''
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  config:
#    import:
#      - "accounts-qa.yml"
#      - "accounts-prod.yml"
#    #Migrated to Configserver
build:
  version: "3.0"

accounts:
  message: "Welcome to accounts microservive related DEV APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@nowhere.com"
  onCallSupport:
    - (801) 555-1234
    - (801) 523-1345