build:
  version: 1.0.0

cards:
  message: "Welcome to cards microservive related PROD APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@nowhere.com"
  onCallSupport:
    - (801) 555-1234
    - (801) 523-1345
