build:
  version: 3.0.0

loans:
  message: "Welcome to loans microservive related DEV APIs "
  contactDetails:
    name: "Rick Frank - DEveloper "
    email: "rick@nowhere.com"
  onCallSupport:
    - (801) 777-9012
    - (801) 333-4234