spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
# File system based configuration
#        native:
#          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/mjlslink/bankapp-config.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
#  rabbitMQ:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

encrypt:
  key: "my-encryption-key-is-symmetric"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    endpoint:
      health:
        probes:
          enabled: true

server:
  port: 8071